### PR TITLE
Issue-250: V2 Migration updates read offsets

### LINKED ISSUE #250: Migration V2 should adjust ordering in read side offsets
**Describe the bug**
In current implementation, it's possible for the journal ordering keys to change (they are a big serial computed on insert).

**To Reproduce**
1. Invoke "nextval" on the postgres sequence without inserting a value (this will "skip" a message, simulating a failed write)
2. Persist an event to the journal via COS, observe journal ordering "2" for that event
3. Add a read side and let it catch up to "2" for that shard/tag
4. Migrate the journal, observe an event ordering value of "1" but an offset of "2" in the read side offsets
5. Persist another event, observe the projection ignore it.

**Expected behavior**
The v2 migration should update the offset store to the new ordering value. As long as the relative ordering of events is maintained, it should suffice to find the new ordering value by inspecting the old journal, finding the persistence ID and sequence_number, then update the offset store to the ordering value from the new journal for that entity/sequence.

### PR DESCRIPTION
**Pull request by zenyui**
Add functionality to migrate the read offsets to the new journal ordering in v2 migration.

resolves #250

### CODE REVIEW

File: code/migration/src/main/scala/com/namely/chiefofstate/migration/versions/v1/V1.scala [hunk 1]
```diff
@@ -141,16 +142,12 @@ object V1 {
...
-          projection_key VARCHAR(255) NOT NULL,
-          current_offset VARCHAR(255) NOT NULL,
-          manifest VARCHAR(4) NOT NULL,
-          mergeable BOOLEAN NOT NULL,
-          last_updated BIGINT NOT NULL,
-          PRIMARY KEY(projection_name, projection_key)
-        )""".withPinnedSession.transactionally
+    // TODO: consider a "current schema" object so v1
+    // migration isn't importing something from v2
+    val stmt = SchemasUtil
```
Comment (Tochemey) [inline code/migration/src/main/scala/com/namely/chiefofstate/migration/versions/v1/V1.scala:147]: I suggest we move the SchemasUtil from v2 then since we are using it everywhere now.

Comment (Tochemey) [reply code/migration/src/main/scala/com/namely/chiefofstate/migration/versions/v1/V1.scala:147]: I think you mean V1Schema here.

**Review by Tochemey — COMMENTED** [review]
Kindly fix the tests that are failing.

**Review by Tochemey — APPROVED** [review]
Great
